GET http://localhost:3000/discdata?q=Wraith


###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "lol@loll.com",
    "password": "poopypoo"
}

###

GET http://localhost:3000/get-discs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NzIzMTI1MTk0NjczMzU2ODEiLCJpYXQiOjE2ODY0MzU3MjJ9.TpwJK-xJf6mftnrvOBa_mVs5xD_jF-Xr7M7XtdxjXZw